webEcom/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using webEcom.Models;

namespace webEcom.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;

        public AboutController(ILogger<AboutController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

webEcom/Controllers/AdminController.cs
// Models/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Mail;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webEcom.Data;
using webEcom.Models;
using Microsoft.VisualBasic;
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using System.Net;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Microsoft.Extensions.Configuration;



namespace webEcom.Controllers
{
    public class AdminController : Controller
    {

        private readonly webEcomDBContext _context;
        private readonly UserManager<Users> _userManager;
        private readonly IConfiguration _configuration;


        public AdminController(webEcomDBContext context, UserManager<Users> userManager, IConfiguration configuration)
        {
            _context = context;
            _userManager = userManager;
            _configuration = configuration;
             
        }

        public async Task<IActionResult> Index()
        {
            var products = await _context.PRODUCT.AsNoTracking().ToListAsync();
            return View(products);
        }


        public IActionResult ProductSendNumber()
        {
            var products = _context.PRODUCT
                .Where(p => p.ProductStatus == "ชำระแล้ว")
                .ToList();
            return View(products);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateProductSendNumber(Dictionary<int, string> ProductSendNumbers)
        {
            foreach (var item in ProductSendNumbers)
            {
                var product = await _context.PRODUCT.FindAsync(item.Key);
                if (product != null)
                {
                    product.ProductSendNumber = item.Value;

                    if(product.ProductSendNumber != null)
                    {
                        product.ProductStatus = "ส่งแล้ว";
                        product.ProductSendTime = DateTime.Now;
                    }
                    
                    _context.Update(product);
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ProductSendNumber));
        }



        public IActionResult bill()
        {
            var pRODUCTS = _context.PRODUCT
                .Where(p => p.ProductStatus == "รอตรวจสอบ")
                .GroupBy(p => new { p.ProductUserTel, p.ProductUserName, p.ProductUserAddress, p.ProductEmail ,p.ProductSendBill})
                .Select(g => new
                {
                    UserTel = g.Key.ProductUserTel,
                    UserName = g.Key.ProductUserName,
                    UserAddress = g.Key.ProductUserAddress,
                    Email = g.Key.ProductEmail,
                    SendBill = g.Key.ProductSendBill,
                    Products = g.ToList()
                })
                .ToList(); 

            return View(pRODUCTS);
        }

        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var product = _context.PRODUCT.Find(productId);
            if (product != null)
            {
                product.ProductStatus = "Market";
                product.ProductUserTel = null;
                product.ProductUserName = null;
                product.ProductUserAddress = null;
                product.ProductEmail = null;
                product.ProductSendBill = null;
                product.ProductUserCart = null;

                _context.SaveChanges();
            }

            return RedirectToAction("bill");
        }


        [HttpPost]
        public async Task<IActionResult> MarkAsPaid(string EmailAndSendBill)
        {
            if (string.IsNullOrEmpty(EmailAndSendBill))
            {
                return BadRequest("Email and SendBill are required.");
            }

            var values = EmailAndSendBill.Split('|');
            if (values.Length != 2)
            {
                return BadRequest("Invalid input format.");
            }

            var Email = values[0];
            if (!DateTime.TryParse(values[1], out var sendBill))
            {
                return BadRequest("Invalid SendBill format.");
            }

            var products = await _context.PRODUCT
                .Where(p => p.ProductEmail == Email && p.ProductStatus == "รอตรวจสอบ" && p.ProductSendBill == sendBill)
                .ToListAsync();

            if (products == null || !products.Any())
            {
                return RedirectToAction(nameof(Index));
            }

            foreach (var product in products)
            {
                product.ProductStatus = "ชำระแล้ว";
                product.ProductBill = DateTime.Now;
                _context.Update(product);
            }

            try
            {
                await _context.SaveChangesAsync();

              
                return RedirectToAction("bill");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error saving changes: {ex.Message}");
                return StatusCode(500, "Internal server error");
            }
        }

        /*
        private void SendInvoiceEmail(string email, byte[] invoicePdf, List<ProductDATA> products)
        {
            var fromAddress = new MailAddress(_configuration["SmtpSettings:Email"], "RyuChuKo");
            var toAddress = new MailAddress(email);
            const string subject = "ใบเสร็จสินค้า";
            var body = "<h1 style='text-align:center;'>รายการสินค้าที่คุณสั่งซื้อ:</h1><br/>";
            float totalPrice = 0;

            body += "<table style='width:100%; border-collapse: collapse;'font-size: 10px;>"
                 + "<tr>"
                 + "<th style='border: 1px solid black; padding: 8px;'>ชื่อสินค้า</th>"
                 + "<th style='border: 1px solid black; padding: 8px;'>ราคา (บาท)</th>"
                 + "</tr>";

            foreach (var item in products)
            {
                body += "<tr>"
                      + $"<td style='border: 1px solid black; padding: 8px;'>{item.ProductName}</td>"
                      + $"<td style='border: 1px solid black; padding: 8px;'>{item.ProductPrice}</td>"
                      + "</tr>";
                totalPrice += item.ProductPrice ?? 0;
            }

            body += "</table>";
            body += $"<h2 >ราคาสินค้ารวมทั้งหมด: {totalPrice} บาท</h2>";
            body += $"<h2 >ชื่อผู้สั่งซื้อ: {products.First().ProductUserName}</h2>";
            body += $"<h2 >เบอร์โทรศัพท์: {products.First().ProductUserTel}</h2>";
            body += $"<h2 >ที่อยู่: {products.First().ProductUserAddress}</h2>";





            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, _configuration["SmtpSettings:Password"])
            };

            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body ,
                IsBodyHtml = true
            })
            {
                message.Attachments.Add(new Attachment(new MemoryStream(invoicePdf), "ใบเสร็จรับเงิน.pdf"));
                smtp.Send(message);
            }
        }
        */


        public async Task<IActionResult> FilterByMarket()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "Market")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public async Task<IActionResult> FilterByInCart()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "In Cart")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public async Task<IActionResult> FilterByรอตรวจสอบ()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "รอตรวจสอบ")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public async Task<IActionResult> FilterByชำระแล้ว()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "ชำระแล้ว")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public async Task<IActionResult> FilterByส่งแล้ว()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "ส่งแล้ว")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public async Task<IActionResult> FilterByส่งสำเร็จแล้ว()
        {
            var pRODUCTS = await _context.PRODUCT
                .Where(p => p.ProductStatus == "ส่งสำเร็จแล้ว")
                .ToListAsync();
            return View("Index", pRODUCTS);
        }

        public IActionResult Search(string querry)
        {
            if (string.IsNullOrEmpty(querry))
            {
                return View("Index", _context.PRODUCT.ToList());
            }

            querry = querry.ToLower();
            var products = _context.PRODUCT.Where(p =>
                (p.ProductType != null && p.ProductType.ToLower().Contains(querry)) ||
                (p.ProductName != null && p.ProductName.ToLower().Contains(querry)) ||
                (p.ProductTag != null && p.ProductTag.ToLower().Contains(querry)) ||
                (p.ProductPrice != null && p.ProductPrice.ToString().Equals(querry))
            ).ToList();

            return View("Index", products);
        }

webEcom/Views/Shared/_AboutLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/About.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Yot_Login2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <!--add login-->
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div>
            @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webEcom/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
</head>
<body>
    <header style="opacity:0; pointer-events: none;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webEcom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
            @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webEcom/Views/Shared/_AccountLayout_Edit.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account_Edit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/EditUser.css" asp-append-version="true" />
</head>
<body>
    <header style="opacity:0; pointer-events: none;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webEcom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webEcom/Views/Shared/_AccountLayout_Edit_Profile.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account_Edit_Profile.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/EditUser.css" asp-append-version="true" />
</head>
<body>
    <header style="opacity:0; pointer-events: none;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webEcom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webEcom/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webEcom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webEcom.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/About.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow w-100 mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/LogoRyuchuko.png" alt="webEcom" style="height:30px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">รายการสินค้า</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="bill">ตรวจสอบการโอนเงิน</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ProductSendNumber">เลขพัสดุ</a>
                        </li>
                        <!--add login-->
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted" >
        <div class="container" style="color:white;font-family: 'Cloud Soft';">
            &copy; 2567 - webEcom - <a asp-area="" asp-controller="About" asp-action="Index" style="color:white;font-family: 'Cloud Soft';">About</a>
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webEcom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=search" />

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webEcom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webEcom.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/About.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/LogoRyuchuko.png" alt="webEcom" style="height:30px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductDATAs" asp-action="Index">ซื้อเลย</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductDATAs" asp-action="Cart">ตะกร้า</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductDATAs" asp-action="ProductStatus">สถานะสินค้า</a>
                        </li>


                        <form asp-controller="ProductDATAs" asp-action="Index" method="get" class="search-form">
                            <div class="input-group input-group-sm mb-3 search-input-group">
                                <input type="text" name="query" class="form-control search-input" placeholder="ค้นหา..." value="@ViewData["CurrentQuery"]" />
                                <button type="submit" class="btn btn-outline-secondary btn-light search-button">
                                    <span class="material-symbols-outlined search-icon">search</span>
                                </button>
                            </div>
                        </form>
                        <!--add login-->
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted " >
        <div class="container" style="color:white;font-family: 'Cloud Soft';">
            &copy; 2567 - webEcom - <a asp-area="" asp-controller="About" asp-action="Index" style="color:white;font-family: 'Cloud Soft';">About</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>